#ifndef TURBO_OCTO_WAFFLE_THE_GAME_ITEMDESCRIPTIONS_H
#define TURBO_OCTO_WAFFLE_THE_GAME_ITEMDESCRIPTIONS_H

typedef enum {
    WEAPON, ARMOR, CONSUMABLES, TOOLS, MISC
} ItemType;

typedef enum {
    BLUNT, SLASH
} DamageType;

#endif //TURBO_OCTO_WAFFLE_THE_GAME_ITEMDESCRIPTIONS_H
