#ifndef TURBO_OCTO_WAFFLE_THE_GAME_LEVELCONFIGURATION_H
#define TURBO_OCTO_WAFFLE_THE_GAME_LEVELCONFIGURATION_H

class LevelConfiguration {

};


#endif //TURBO_OCTO_WAFFLE_THE_GAME_LEVELCONFIGURATION_H
